- path: /groups/hess/hess_collaborators/Annotations/ParentFiles_whole-cell_images/8x8x8nm_Data/Cell21_FIB.n5
  resolution:
    x: 8
    y: 8
    z: 8
  mask_params:
    needs_mask: false
    mask_threshold: 0.0
- path: /groups/hess/hess_collaborators/Annotations/ParentFiles_whole-cell_images/Chlamydomonas/Chlamydomonas_4x4x4nm.n5
  resolution:
    x: 4
    y: 4
    z: 4
  mask_params:
    needs_mask: false
    mask_threshold: 0.0
- path: /groups/hess/hess_collaborators/Annotations/ParentFiles_whole-cell_images/HeLa_Cell2_4x4x4nm/Aubrey_17-7_17_Cell2_4x4x4nm.n5
  resolution:
    x: 4
    y: 4
    z: 4
  mask_params:
    needs_mask: false
    mask_threshold: 0.0
- path: /groups/hess/hess_collaborators/Annotations/ParentFiles_whole-cell_images/HeLa_Cell3_4x4x4nm/Aubrey_17-7_17_Cell3_4x4x4nm.n5
  resolution:
    x: 4
    y: 4
    z: 4
  mask_params:
    needs_mask: false
    mask_threshold: 0.0
- path: /groups/hess/hess_collaborators/Annotations/ParentFiles_whole-cell_images/Jurkat_Cell1_4x4x4nm/Jurkat_Cell1_FS96-Area1_4x4x4nm.n5
  resolution:
    x: 4
    y: 4
    z: 4
  mask_params:
    needs_mask: false
    mask_threshold: 0.0
- path: /groups/hess/hess_collaborators/Annotations/ParentFiles_whole-cell_images/Macrophage_FS80_Cell2_4x4x4nm/Cryo_FS80_Cell2_4x4x4nm.n5
  resolution:
    x: 4
    y: 4
    z: 4
  mask_params:
    needs_mask: false
    mask_threshold: 0.0
- path: /groups/hess/hess_collaborators/Annotations/ParentFiles_whole-cell_images/Mouse_NA3-3_4x4x4nm/Mouse_NA3-3_4x4x4nm.n5
  resolution:
    x: 4
    y: 4
    z: 4
  mask_params:
    needs_mask: false
    mask_threshold: 0.0
- path: /groups/hess/hess_collaborators/Annotations/ParentFiles_whole-cell_images/Pancreas_Islets/Pancreas_G36-2_4x4x4nm.n5
  resolution:
    x: 4
    y: 4
    z: 4
  mask_params:
    needs_mask: false
    mask_threshold: 0.0
- path: /groups/hess/hess_collaborators/Annotations/ParentFiles_whole-cell_images/TWalther_WT45_Cell2_4x4x4nm/Cryo_20171009_WT45_Cell2_4x4x4nm.n5
  resolution:
    x: 4
    y: 4
    z: 4
  mask_params:
    needs_mask: false
    mask_threshold: 0.0
